export const LOCATIONS = [
  'Main Block (Academic)',
  'Hi-Tech Block (Academic)',
  'Tech Park (Academic)',
  'University Building (UB)',
  'PG Block (Academic)',
  'Civil Engineering Block',
  'Mechanical Block (A/B/C)',
  'Electrical Science Block',
  'Technology Park (TP)',
  'School of Architecture',
  'School of Management',
  'Institute of Hotel Mgmt',
  'Arts & Science College',
  'Science & Humanities Block',
  'Medical Institution Block',
  'SRM General Hospital',
  'Dental Clinical Block',
  'Dr. T.P. Ganesan Auditorium',
  'Central Library',
  'ESAN Hostel (Boys)',
  'Magan Hostel (Boys)',
  'Pierre Hostel (Boys)',
  'Kaari Hostel (Boys)',
  'Adhiyaman Hostel (Boys)',
  'Nelson Mandela Hostel',
  'Agathiyar Hostel (Boys)',
  'Senbagam Hostel (Boys)',
  'MGR Hostel (Boys)',
  'Kanniyagi Hostel (Girls)',
  'Aravindar Block (Girls)',
  'Manoranjitham Hostel (Girls)',
  'Mullai Hostel (Girls)',
  'Thamara Hostel (Girls)',
  'Malligai Hostel (Girls)',
  'Meenakshi Hostel (Girls)',
  'Main Food Court',
  'TP Canteen',
  'UB Canteen',
  'Medical Canteen',
  'International Hostel',
  'SRM Hotel',
  'Placement Cell',
  'City Union Bank / Supermarket',
  'Sports Hangar / Stadium',
  'Basketball Court',
  'Potheri Station Gate',
  'Main Gate (Abode Road)',
];
